# Generated by Django 5.1.6 on 2025-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('science', 'Наука'), ('space', 'Космос'), ('biology', 'Биология'), ('history', 'История')], default='science', max_length=50)),
                ('text', models.TextField()),
                ('voice', models.CharField(default='default', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
