# Generated by Django 5.1.6 on 2025-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='background_image',
        ),
        migrations.AddField(
            model_name='video',
            name='background_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='background_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='background_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
