# Generated by Django 5.1.6 on 2025-02-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='theme',
            field=models.CharField(default='Общая', max_length=100),
        ),
    ]
