# Generated by Django 5.1.6 on 2025-02-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_audio_file_video_background_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='music_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
