# Generated by Django 5.1.6 on 2025-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_music_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tiktok_description',
            field=models.TextField(default=''),
        ),
    ]
