# Generated by Django 5.1.6 on 2025-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_tiktok_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ssml_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
