# Generated by Django 5.1.6 on 2025-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_ssml_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='background_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='background_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_4_prompt',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_4_text',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_5_prompt',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_5_text',
            field=models.TextField(default='Нет данных'),
        ),
    ]
